object ViewTelaFundo: TViewTelaFundo
  Left = 0
  Top = 0
  Align = alClient
  AlphaBlend = True
  AlphaBlendValue = 100
  BorderStyle = bsNone
  Caption = 'ViewTelaFundo'
  ClientHeight = 486
  ClientWidth = 806
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
end
